#Cloud-Config File 
# Defualt Password ~> Aguilar 

users:
        -name: core
        passwd: $1$8QrwgvPU$tqFPKWsqoq967.6NCYxsn/
        groups:
                -wheel
                -docker
                -fleet  #May be deprecated (July 23,2018) 
                -rkt
        -name: user
        passwd: $1$8QrwgvPU$tqFPKWsqoq967.6NCYxsn/
        groups:
                -wheel
                -docker
                -fleet
                -rkt
