#!cloud-config 
# Defualt Password ~> Aguilar 

users:
        -name: core
        passwd: $1$/CLwNbUJ$5lXSEwjkOBTBiJ3SCvc8k1
        groups:
                -wheel
                -docker
                -fleet  #May be deprecated (July 23,2018) 
                -rkt

        -name: user
        passwd: $1$/CLwNbUJ$5lXSEwjkOBTBiJ3SCvc8k1
        groups:
                -wheel
                -docker
                -fleet
                -rkt

